services:
  - type: web
    name: datumagro-web
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "8000"
