# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INADIMPLENTE', 'Inadimplente'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateTimeField()),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Digital', 'Digital'), ('Conectado', 'Conectado'), ('Elite', 'Elite')], max_length=100, unique=True)),
                ('descricao', models.TextField(help_text='Descrição comercial do plano para o site.')),
                ('valor_base_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_animais', models.PositiveIntegerField(help_text='Limite de animais monitorados neste plano.')),
                ('hardware_incluso', models.BooleanField(default=False, help_text='Nosso modelo inovador HaaS: Vexus fornece os brincos, eliminando a barreira de entrada.')),
                ('suporte_especialista', models.BooleanField(default=False, help_text='Diferencial do Plano Elite: Acesso a veterinários e zootecnistas parceiros.')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['valor_base_mensal'],
            },
        ),
    ]
