# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assinaturas', '0001_initial'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='cadastros.cliente'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='assinaturas.plano'),
        ),
    ]
