# Generated by Django 5.2.8 on 2025-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='acesso_importacao_internacional',
            field=models.BooleanField(default=False, help_text='Habilita o módulo de importação internacional para o cliente (ex.: Planos Enterprise/Elite).'),
        ),
        migrations.AddField(
            model_name='plano',
            name='max_funcionarios',
            field=models.PositiveIntegerField(default=0, help_text="Número máximo de usuários do tipo 'funcionário' permitidos além do usuário master. 0 significa nenhum funcionário permitido."),
        ),
        migrations.AlterField(
            model_name='plano',
            name='limite_animais',
            field=models.PositiveIntegerField(blank=True, help_text='Limite de animais monitorados neste plano. Null significa sem limite (ilimitado).', null=True),
        ),
    ]
