# Generated by Django 5.2.7 on 2026-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0004_plano_app_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Exibir este plano em destaque ("Mais popular") no app'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='recursos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de recursos exibidos no app. Ex: ["Gestão de animais", "Mapa interativo"]'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='whatsapp_msg',
            field=models.CharField(blank=True, default='', help_text='Mensagem URL-encoded para WhatsApp ao clicar em "Consultar". Deixe vazio para usar o padrão.', max_length=500),
        ),
    ]
