# Generated by Django 5.2.7 on 2025-10-27 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('BL', 'Boleto'), ('PX', 'PIX')], max_length=2)),
                ('titular', models.CharField(max_length=255)),
                ('numero_cartao', models.CharField(blank=True, max_length=20, null=True)),
                ('validade', models.CharField(blank=True, max_length=7, null=True)),
                ('bandeira', models.CharField(blank=True, max_length=50, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['-principal', '-data_cadastro'],
            },
        ),
    ]
