# Generated by Django 5.2.8 on 2026-06-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_formapagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='categoria_nome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default='DESPESA', max_length=10),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='financeiro.categoria'),
        ),
    ]
