# Generated by Django 5.2.7 on 2025-11-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0007_animal_animal_brinco_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_embarque', models.CharField(max_length=20, unique=True, verbose_name='Número do Embarque')),
                ('tipo', models.CharField(choices=[('EXP', 'Exportação (Saída)'), ('IMP', 'Importação (Entrada)')], max_length=3)),
                ('status', models.CharField(choices=[('PLA', 'Planejado'), ('PRE', 'Pré-Embarque / Quarentena'), ('NAV', 'Em Trânsito Marítimo'), ('POR', 'Chegada no Porto'), ('FIN', 'Finalizado / Desembaraçado'), ('CAN', 'Cancelado')], default='PLA', max_length=3)),
                ('porto_origem', models.CharField(default='Porto do Açu', max_length=100)),
                ('porto_destino', models.CharField(max_length=100)),
                ('pais_parceiro', models.CharField(max_length=100, verbose_name='País Origem/Destino')),
                ('navio', models.CharField(blank=True, max_length=100, null=True)),
                ('viagem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Viagem')),
                ('data_prevista_embarque', models.DateField(verbose_name='Data Prevista de Embarque')),
                ('data_prevista_chegada', models.DateField(verbose_name='Data Prevista de Chegada')),
                ('data_real_embarque', models.DateField(blank=True, null=True, verbose_name='Data Real de Embarque')),
                ('data_real_chegada', models.DateField(blank=True, null=True, verbose_name='Data Real de Chegada')),
                ('agente_carga', models.CharField(blank=True, max_length=200, verbose_name='Agente de Carga')),
                ('bl_numero', models.CharField(blank=True, max_length=50, verbose_name='Bill of Lading')),
                ('conhecimento_carga', models.CharField(blank=True, max_length=50, verbose_name='Conhecimento de Carga')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Frete (USD)')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Seguro (USD)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total (USD)')),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarques', to='cadastros.cliente')),
            ],
            options={
                'verbose_name': 'Embarque',
                'verbose_name_plural': 'Embarques',
                'ordering': ['-data_prevista_embarque'],
            },
        ),
        migrations.CreateModel(
            name='ItemEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto', models.CharField(choices=[('VIVO', 'Gado Vivo'), ('CARNE', 'Carne/Carcaça'), ('CORTES', 'Cortes Específicos'), ('SUB', 'Subprodutos')], default='VIVO', max_length=10)),
                ('descricao_produto', models.CharField(blank=True, help_text='Ex: Carcaça Nelore, Cortes Traseiros, Couro', max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, help_text='Quantidade de unidades ou toneladas', max_digits=10)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Total (kg)')),
                ('categoria_carne', models.CharField(blank=True, help_text='Ex: Prime Cut, Choice, Select', max_length=50)),
                ('certificacao', models.CharField(blank=True, help_text='Ex: Halal, Kosher, Organic', max_length=100)),
                ('gta_numero', models.CharField(blank=True, max_length=50, verbose_name='Número GTA')),
                ('certificado_sanitario', models.FileField(blank=True, null=True, upload_to='docs_logistica/certificados/')),
                ('certificado_origem', models.FileField(blank=True, null=True, upload_to='docs_logistica/origem/')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário (USD)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total (USD)')),
                ('observacoes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_logistica', to='cadastros.animal')),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='logistica.embarque')),
            ],
            options={
                'verbose_name': 'Item de Embarque',
                'verbose_name_plural': 'Itens de Embarque',
            },
        ),
        migrations.CreateModel(
            name='RastreamentoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('PLA', 'Planejado'), ('PRE', 'Pré-Embarque / Quarentena'), ('NAV', 'Em Trânsito Marítimo'), ('POR', 'Chegada no Porto'), ('FIN', 'Finalizado / Desembaraçado'), ('CAN', 'Cancelado')], max_length=3)),
                ('status_novo', models.CharField(choices=[('PLA', 'Planejado'), ('PRE', 'Pré-Embarque / Quarentena'), ('NAV', 'Em Trânsito Marítimo'), ('POR', 'Chegada no Porto'), ('FIN', 'Finalizado / Desembaraçado'), ('CAN', 'Cancelado')], max_length=3)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(blank=True, help_text='Localização atual', max_length=100)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='docs_logistica/rastreamento/')),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rastreamento', to='logistica.embarque')),
            ],
            options={
                'verbose_name': 'Rastreamento de Embarque',
                'verbose_name_plural': 'Rastreamento de Embarques',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.AddIndex(
            model_name='embarque',
            index=models.Index(fields=['numero_embarque'], name='logistica_e_numero__d0a1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='embarque',
            index=models.Index(fields=['tipo', 'status'], name='logistica_e_tipo_c0d6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='embarque',
            index=models.Index(fields=['data_prevista_embarque'], name='logistica_e_data_pr_d627f9_idx'),
        ),
        migrations.AddIndex(
            model_name='embarque',
            index=models.Index(fields=['responsavel'], name='logistica_e_respons_aca7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='itemembarque',
            index=models.Index(fields=['embarque', 'tipo_produto'], name='logistica_i_embarqu_b08b30_idx'),
        ),
        migrations.AddIndex(
            model_name='itemembarque',
            index=models.Index(fields=['animal'], name='logistica_i_animal__4a8952_idx'),
        ),
    ]
