# Generated by Django 5.2.7 on 2025-11-21 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_animal_animal_brinco_idx_and_more'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbarqueLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_controle', models.CharField(max_length=50, unique=True, verbose_name='Nº Processo/DUE')),
                ('tipo', models.CharField(choices=[('EXP', 'Exportação (Saída)'), ('IMP', 'Importação (Entrada)')], default='EXP', max_length=3)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Navio'), ('EMBARCADO', 'Embarcado / Em Trânsito'), ('FINALIZADO', 'Finalizado')], default='AGUARDANDO', max_length=20)),
                ('porto_origem', models.CharField(default='Porto do Açu (RJ)', max_length=100)),
                ('porto_destino', models.CharField(max_length=100, verbose_name='Porto de Destino')),
                ('navio', models.CharField(max_length=100)),
                ('data_prevista', models.DateField()),
                ('parceiro_comercial', models.CharField(blank=True, max_length=200, verbose_name='Importador/Exportador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_produto', models.CharField(blank=True, help_text='Ex: Carcaça Resfriada, Sêmen', max_length=200)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor (USD)')),
                ('gta', models.CharField(blank=True, max_length=50, verbose_name='Nº GTA')),
                ('sif', models.CharField(blank=True, max_length=50, verbose_name='Nº SIF (se carne)')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportacoes', to='cadastros.animal')),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='logistica.embarquelogistica')),
            ],
        ),
    ]
