# Generated by Django 5.2.8 on 2025-11-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_embarquelogistica_itemcarga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarga',
            name='embarque',
        ),
        migrations.RemoveField(
            model_name='itemcarga',
            name='animal',
        ),
        migrations.RenameField(
            model_name='itemembarque',
            old_name='gta_numero',
            new_name='gta',
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='sif',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número SIF'),
        ),
        migrations.DeleteModel(
            name='EmbarqueLogistica',
        ),
        migrations.DeleteModel(
            name='ItemCarga',
        ),
    ]
