# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('animais', models.ManyToManyField(blank=True, related_name='lotes', to='cadastros.animal')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='cadastros.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='Piquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_capim', models.CharField(choices=[('MOMBASSA', 'Mombaça'), ('PIATA', 'BRS Piatã'), ('ZURI', 'BRS Zuri'), ('MARANDU', 'Marandu')], max_length=20)),
                ('status', models.CharField(choices=[('DESCANSANDO', 'Descansando'), ('EM_USO', 'Em Uso'), ('PRONTO', 'Pronto para Uso')], default='DESCANSANDO', max_length=20)),
                ('data_entrada_lote', models.DateField(blank=True, null=True)),
                ('data_saida_prevista', models.DateField(blank=True, null=True)),
                ('lote_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piquete_atual', to='operacional.lote')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piquetes', to='cadastros.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('tipo_produto', models.CharField(choices=[('VACINA', 'Vacina'), ('VERMIFUGO', 'Vermífugo'), ('ANTIBIOTICO', 'Antibiótico'), ('OUTRO', 'Outro')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_sanitarios', to='cadastros.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ManejoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField()),
                ('dose', models.CharField(help_text='Ex: 5ml', max_length=50)),
                ('observacao', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejos_sanitarios', to='cadastros.animal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.produtosanitario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroReprodutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('COBERTURA', 'Cobertura Natural'), ('INSEMINACAO', 'Inseminação Artificial'), ('DIAGNOSTICO', 'Diagnóstico de Gestação'), ('PARTO', 'Parto')], max_length=20)),
                ('data_evento', models.DateField()),
                ('resultado_dg', models.CharField(blank=True, choices=[('PRENHA', 'Prenha'), ('VAZIA', 'Vazia')], max_length=10, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('matriz', models.ForeignKey(limit_choices_to={'sexo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='registros_reprodutivos', to='cadastros.animal')),
                ('touro', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coberturas', to='cadastros.animal')),
            ],
        ),
    ]
