# Generated by Django 5.2.6 on 2025-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroreprodutivo',
            options={'ordering': ['-data_evento']},
        ),
        migrations.AddField(
            model_name='registroreprodutivo',
            name='ordem_parto',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Calculado automaticamente. Ex: 1 para a primeira cria.', null=True),
        ),
    ]
