# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('inteligencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push Notification')], max_length=10)),
                ('destinatario', models.CharField(help_text='E-mail ou número de telefone para o qual a notificação foi enviada.', max_length=255)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado com Sucesso'), ('FALHA', 'Falha no Envio')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detalhes_retorno', models.TextField(blank=True, help_text='Resposta da API externa (ex: Twilio SID ou erro SMTP).')),
                ('alerta_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to='inteligencia.alerta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-timestamp'],
            },
        ),
    ]
