# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email_contato', models.EmailField(max_length=254, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_propriedade', models.CharField(max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('objetivo_producao', models.CharField(blank=True, choices=[('CRIA', 'Cria'), ('RECRIA', 'Recria'), ('ENGORDA', 'Engorda')], max_length=10, null=True)),
                ('tipo_solo', models.CharField(blank=True, choices=[('ARENOSO', 'Arenoso'), ('ARGILOSO', 'Argiloso'), ('MISTO', 'Misto')], max_length=10, null=True)),
                ('topografia', models.CharField(blank=True, choices=[('PLANO', 'Plano'), ('ONDULADO', 'Ondulado'), ('MONTANHOSO', 'Montanhoso')], max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='RegistroPesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pesagem', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de Pesagem',
                'verbose_name_plural': 'Registros de Pesagem',
                'ordering': ['-data_pesagem'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinco', models.CharField(help_text='Identificação única do animal (brinco, tatuagem, etc).', max_length=50)),
                ('raca', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o animal está ativo na fazenda.')),
                ('mae', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendentes_mae', to='cadastros.animal')),
                ('pai', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendentes_pai', to='cadastros.animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-data_nascimento'],
            },
        ),
    ]
