# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perfil_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='cadastros.cliente'),
        ),
        migrations.AddField(
            model_name='animal',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='cadastros.propriedade'),
        ),
        migrations.AddField(
            model_name='registropesagem',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesagens', to='cadastros.animal'),
        ),
        migrations.AlterUniqueTogether(
            name='propriedade',
            unique_together={('cliente', 'nome_propriedade')},
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('propriedade', 'brinco')},
        ),
    ]
