# Generated by Django 5.2.6 on 2025-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='perfil_usuario',
        ),
        migrations.AddField(
            model_name='animal',
            name='caracteristicas_adicionais',
            field=models.TextField(blank=True, help_text="Descreva outros comportamentos (ex: 'Foge no curral', 'Bom de criar') ou características físicas."),
        ),
        migrations.AddField(
            model_name='animal',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto opcional do animal.', null=True, upload_to='animais_fotos/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='temperamento',
            field=models.CharField(blank=True, choices=[('MANSO', 'Manso'), ('NORMAL', 'Normal'), ('BRABO', 'Brabo'), ('AGRESSIVO', 'Agressivo')], help_text='Temperamento principal do animal.', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='brinco',
            field=models.CharField(help_text='Identificação única do animal.', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(choices=[('NELORE', 'Nelore'), ('ANGUS', 'Angus'), ('BRAHMAN', 'Brahman'), ('BRANGUS', 'Brangus'), ('SENEPOL', 'Senepol'), ('GUZERA', 'Guzerá'), ('TABAPUA', 'Tabapuã'), ('GIR', 'Gir Leiteiro'), ('GIROLANDO', 'Girolando'), ('HEREFORD', 'Hereford'), ('BRAFORD', 'Braford'), ('CARACU', 'Caracu'), ('OUTRA', 'Outra/Mestiço')], max_length=100),
        ),
    ]
