# Generated by Django 5.2.6 on 2025-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_cliente_perfil_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aptidao',
            field=models.CharField(blank=True, choices=[('CORTE', 'Corte'), ('LEITE', 'Leite'), ('DUPLA', 'Dupla Aptidão')], max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='categoria',
            field=models.CharField(blank=True, choices=[('BEZERRO', 'Bezerro(a)'), ('NOVILHA', 'Novilha'), ('GARROTE', 'Garrote'), ('TOURO', 'Touro'), ('MATRIZ', 'Matriz (Vaca)'), ('BOI', 'Boi (Engorda)')], max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='status_reprodutivo',
            field=models.CharField(blank=True, choices=[('VAZIA', 'Vazia'), ('PRENHA', 'Prenha'), ('LACTANTE', 'Em Lactação'), ('SECA', 'Seca')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='caracteristicas_adicionais',
            field=models.TextField(blank=True, help_text='Descreva outros comportamentos ou características físicas.'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='temperamento',
            field=models.CharField(blank=True, choices=[('MANSO', 'Manso'), ('NORMAL', 'Normal'), ('BRABO', 'Brabo'), ('AGRESSIVO', 'Agressivo')], max_length=20),
        ),
    ]
