# Generated by Django 5.2.6 on 2025-10-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_animal_aptidao_animal_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_reprodutor',
            field=models.BooleanField(default=False, help_text='Marque se este macho é um reprodutor (touro).'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status_reprodutivo',
            field=models.CharField(blank=True, choices=[('VAZIA', 'Vazia'), ('PRENHA', 'Prenha'), ('LACTANTE', 'Em Lactação'), ('SECA', 'Seca')], help_text='Apenas para fêmeas em idade reprodutiva.', max_length=10),
        ),
    ]
