# Generated by Django 5.2.7 on 2025-10-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_animal_is_reprodutor_alter_animal_status_reprodutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
