# Generated by Django 5.2.7 on 2025-11-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_animal_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['brinco'], name='animal_brinco_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['propriedade', 'ativo'], name='animal_prop_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['raca', 'sexo'], name='animal_raca_sexo_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['categoria'], name='animal_categoria_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status_reprodutivo'], name='animal_status_reprod_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['data_nascimento'], name='animal_data_nasc_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['pai'], name='animal_pai_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['mae'], name='animal_mae_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['propriedade', 'raca', 'sexo'], name='animal_prop_raca_sexo_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['propriedade', 'data_nascimento'], name='animal_prop_data_nasc_idx'),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['cliente'], name='propriedade_cliente_idx'),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['estado', 'cidade'], name='propriedade_estado_cidade_idx'),
        ),
        migrations.AddIndex(
            model_name='propriedade',
            index=models.Index(fields=['objetivo_producao'], name='propriedade_objetivo_idx'),
        ),
        migrations.AddIndex(
            model_name='registropesagem',
            index=models.Index(fields=['animal', '-data_pesagem'], name='pesagem_animal_data_idx'),
        ),
        migrations.AddIndex(
            model_name='registropesagem',
            index=models.Index(fields=['-data_pesagem'], name='pesagem_data_idx'),
        ),
        migrations.AddIndex(
            model_name='registropesagem',
            index=models.Index(fields=['animal', 'peso_kg'], name='pesagem_animal_peso_idx'),
        ),
    ]
