# Generated by Django 5.2.8 on 2025-12-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_animal_animal_brinco_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('periodo_dose_dias', models.PositiveIntegerField(blank=True, help_text='Período entre doses em dias', null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
            },
        ),
        migrations.CreateModel(
            name='InformacaoGenetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_genealogico', models.CharField(blank=True, help_text='Número do registro genealógico', max_length=100)),
                ('associacao_genealogica', models.CharField(blank=True, help_text='Associação responsável', max_length=100)),
                ('frame_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cebvs', models.DecimalField(blank=True, decimal_places=2, help_text='CEBVs - Expected Breeding Values', max_digits=5, null=True)),
                ('peso_205_dias', models.DecimalField(blank=True, decimal_places=2, help_text='Peso esperado aos 205 dias', max_digits=6, null=True)),
                ('peso_365_dias', models.DecimalField(blank=True, decimal_places=2, help_text='Peso esperado aos 365 dias', max_digits=6, null=True)),
                ('peso_550_dias', models.DecimalField(blank=True, decimal_places=2, help_text='Peso esperado aos 550 dias', max_digits=6, null=True)),
                ('marmoreio', models.DecimalField(blank=True, decimal_places=1, help_text='Grau de marmoreio (1-5)', max_digits=3, null=True)),
                ('area_olho_lombo', models.DecimalField(blank=True, decimal_places=2, help_text='Área do olho do lombo (cm²)', max_digits=5, null=True)),
                ('fertilidade', models.DecimalField(blank=True, decimal_places=2, help_text='Índice de fertilidade', max_digits=5, null=True)),
                ('temperamento_genetico', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('eficiencia_alimentar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dna_coleta', models.BooleanField(default=False)),
                ('data_coleta_dna', models.DateField(blank=True, null=True)),
                ('marcadores_moleculares', models.TextField(blank=True, help_text='Resultados de marcadores moleculares')),
                ('observacoes_geneticas', models.TextField(blank=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacao_genetica', to='cadastros.animal')),
            ],
            options={
                'verbose_name': 'Informação Genética',
                'verbose_name_plural': 'Informações Genéticas',
            },
        ),
        migrations.CreateModel(
            name='Piquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipo_vegetacao', models.CharField(blank=True, help_text='Tipo de vegetação/pasto', max_length=100)),
                ('capacidade_maxima', models.PositiveIntegerField(blank=True, help_text='Capacidade máxima de animais', null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piquetes_cadastro', to='cadastros.propriedade')),
            ],
            options={
                'verbose_name': 'Piquete',
                'verbose_name_plural': 'Piquetes',
                'unique_together': {('propriedade', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='FichaTecnicaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada_piquete', models.DateField(blank=True, null=True)),
                ('peso_atual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('data_ultima_pesagem', models.DateField(blank=True, null=True)),
                ('gmd_diario', models.DecimalField(blank=True, decimal_places=3, help_text='Ganho Médio Diário (kg/dia)', max_digits=5, null=True)),
                ('gmd_semanal', models.DecimalField(blank=True, decimal_places=3, help_text='Ganho Médio Semanal (kg/semana)', max_digits=5, null=True)),
                ('gmd_quinzenal', models.DecimalField(blank=True, decimal_places=3, help_text='Ganho Médio Quinzenal (kg/quinzena)', max_digits=5, null=True)),
                ('gmd_mensal', models.DecimalField(blank=True, decimal_places=3, help_text='Ganho Médio Mensal (kg/mês)', max_digits=5, null=True)),
                ('gmd_anual', models.DecimalField(blank=True, decimal_places=3, help_text='Ganho Médio Anual (kg/ano)', max_digits=5, null=True)),
                ('status_saude', models.CharField(choices=[('SAUDAVEL', 'Saudável'), ('DOENTE', 'Doente'), ('RECUPERANDO', 'Em Recuperação'), ('CRONICO', 'Problema Crônico')], default='SAUDAVEL', max_length=50)),
                ('vacinas_em_dia', models.BooleanField(default=True)),
                ('proxima_vacina', models.DateField(blank=True, null=True)),
                ('observacoes_saude', models.TextField(blank=True)),
                ('racao_diaria_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('suplementacao', models.TextField(blank=True, help_text='Suplementos minerais, vitamínicos, etc.')),
                ('consumo_pasto', models.BooleanField(default=True, help_text='Se consome pasto ou só ração')),
                ('producao_leite_diaria', models.DecimalField(blank=True, decimal_places=2, help_text='Para fêmeas leiteiras', max_digits=6, null=True)),
                ('ultima_ordemha', models.DateTimeField(blank=True, null=True)),
                ('custo_diario', models.DecimalField(blank=True, decimal_places=2, help_text='Custo diário de manutenção', max_digits=8, null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de mercado estimado', max_digits=10, null=True)),
                ('comportamento_piquete', models.TextField(blank=True, help_text='Como se comporta no piquete')),
                ('hierarquia_social', models.CharField(blank=True, help_text='Posição na hierarquia do grupo', max_length=50)),
                ('numero_cobricoes', models.PositiveIntegerField(default=0, help_text='Número de cobrições realizadas')),
                ('taxa_concepcao', models.DecimalField(blank=True, decimal_places=2, help_text='Taxa de concepção (%)', max_digits=5, null=True)),
                ('historico_clinico', models.TextField(blank=True, help_text='Histórico de doenças, tratamentos, etc.')),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel_atualizacao', models.CharField(blank=True, max_length=100)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='cadastros.animal')),
                ('piquete_atual', models.ForeignKey(blank=True, help_text='Piquete onde o animal está atualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_atuais', to='cadastros.piquete')),
            ],
            options={
                'verbose_name': 'Ficha Técnica do Animal',
                'verbose_name_plural': 'Fichas Técnicas dos Animais',
            },
        ),
        migrations.CreateModel(
            name='AplicacaoVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField()),
                ('dose', models.CharField(blank=True, help_text='Número da dose ou reforço', max_length=50)),
                ('lote', models.CharField(blank=True, help_text='Lote da vacina', max_length=50)),
                ('veterinario', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes_vacina', to='cadastros.animal')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.vacina')),
            ],
            options={
                'verbose_name': 'Aplicação de Vacina',
                'verbose_name_plural': 'Aplicações de Vacinas',
                'ordering': ['-data_aplicacao'],
            },
        ),
    ]
