# Generated by Django 5.2.8 on 2026-06-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_vacina_informacaogenetica_piquete_fichatecnicaanimal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='registro_genetico',
            field=models.CharField(blank=True, choices=[('PO', 'Puro de Origem (PO)'), ('PC', 'Puro por Cruza (PC)'), ('PA', 'Puro por Absorção (PA)'), ('COM', 'Comercial (sem registro)')], default='COM', help_text='Classificação genética do animal conforme associação de raça.', max_length=3),
        ),
        migrations.AddField(
            model_name='registropesagem',
            name='gmd_calculado',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='GMD calculado automaticamente em relação à pesagem anterior (kg/dia).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='registropesagem',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('RFID', 'Balança RFID')], default='MANUAL', max_length=10),
        ),
    ]
