# Generated by Django 5.2.8 on 2026-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_add_registro_genetico_gmd_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
