# Generated by Django 5.2.8 on 2026-06-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_data_nascimento_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='emite_nota_fiscal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='faixa_rebanho',
            field=models.CharField(blank=True, choices=[('1-50', '1 a 50'), ('51-200', '51 a 200'), ('201-500', '201 a 500'), ('501-1000', '501 a 1000'), ('1000+', 'Acima de 1000')], max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='num_funcionarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='onboarding_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='onboarding_etapa',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='principal_desafio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sistema_anterior',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=4),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='tipo_operacao',
            field=models.CharField(choices=[('CORTE', 'Corte'), ('LEITE', 'Leite'), ('MISTO', 'Misto')], default='CORTE', max_length=20),
        ),
    ]
