# Generated by Django 5.2.8 on 2026-08-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_especie',
            field=models.CharField(choices=[('BOVINOS_CORTE', 'Pecuária de Corte (Bovinos)'), ('BOVINOS_LEITE', 'Pecuária de Leite (Bovinos)'), ('SUINOS', 'Suinocultura (Porcos)'), ('EQUINOS', 'Equinocultura (Cavalos)'), ('OVINOS_CAPRINOS', 'Ovinos e Caprinos (Ovelhas/Cabras)')], default='BOVINOS_CORTE', max_length=20),
        ),
    ]
