# Generated by Django 5.2.7 on 2026-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_cliente_status_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='aptidao',
            field=models.CharField(blank=True, choices=[('CORTE', 'Corte'), ('LEITE', 'Leite'), ('DUPLA', 'Dupla Aptidão'), ('TRABALHO', 'Trabalho'), ('ESPORTE', 'Esporte / Lazer'), ('LA', 'Lã'), ('REPRODUCAO', 'Reprodução'), ('CARNE', 'Carne')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(blank=True, choices=[('BEZERRO', 'Bezerro(a)'), ('NOVILHA', 'Novilha'), ('GARROTE', 'Garrote'), ('TOURO', 'Touro'), ('MATRIZ', 'Matriz (Vaca)'), ('BOI', 'Boi (Engorda)'), ('POTRO', 'Potro/Potranca'), ('CAPAO', 'Capão'), ('EGUA', 'Égua'), ('GARANHAO', 'Garanhão'), ('LEITAO', 'Leitão'), ('SUINO_CRESC', 'Em Crescimento'), ('SUINO_TERM', 'Em Terminação'), ('PORCA', 'Porca'), ('VARRAO', 'Varrão'), ('CORDEIRO', 'Cordeiro/Cabrito'), ('OVELHA', 'Ovelha/Cabra'), ('CARNEIRO', 'Carneiro/Bode')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(choices=[('NELORE', 'Nelore'), ('ANGUS', 'Angus'), ('BRAHMAN', 'Brahman'), ('BRANGUS', 'Brangus'), ('SENEPOL', 'Senepol'), ('GUZERA', 'Guzerá'), ('TABAPUA', 'Tabapuã'), ('GIR', 'Gir'), ('BRAFORD', 'Braford'), ('HEREFORD', 'Hereford'), ('CARACU', 'Caracu'), ('GIROLANDO', 'Girolando'), ('HOLANDES', 'Holandês (PB)'), ('JERSEY', 'Jersey'), ('PARDO_SUICO', 'Pardo Suíço'), ('QUARTO_MILHA', 'Quarto de Milha'), ('CRIOULO', 'Crioulo'), ('PAINT_HORSE', 'Paint Horse'), ('MANGALARGA', 'Mangalarga Marchador'), ('ARABE', 'Árabe'), ('PSI', 'PSI (Puro Sangue Inglês)'), ('LUSITANO', 'Lusitano'), ('APPALOOSA', 'Appaloosa'), ('CAMPOLINA', 'Campolina'), ('SELA_BR', 'Sela Brasileira'), ('LANDRACE', 'Landrace'), ('LARGE_WHITE', 'Large White'), ('PIETRAIN', 'Pietrain'), ('DUROC', 'Duroc'), ('HAMPSHIRE', 'Hampshire'), ('MOURA', 'Moura'), ('PIAU', 'Piau'), ('DORPER', 'Dorper'), ('SANTA_INES', 'Santa Inês'), ('TEXEL', 'Texel'), ('ILE_FRANCE', 'Ile de France'), ('SUFFOLK', 'Suffolk'), ('BERGAMASCA', 'Bergamasca'), ('BOER', 'Boer'), ('ANGLO_NUB', 'Anglo-Nubiano'), ('SAANEN', 'Saanen'), ('TOGGENBURG', 'Toggenburg'), ('ALPINA_BR', 'Alpina Brasileira'), ('OUTRA', 'Outra/Mestiço')], max_length=100),
        ),
    ]
