# Generated by Django 5.2.7 on 2025-11-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cadastros', '0007_animal_animal_brinco_idx_and_more'),
        ('usuarios', '0002_usuario_data_nascimento_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuário'},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo/posição do funcionário na propriedade', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='setor',
            field=models.CharField(blank=True, choices=[('producao', 'Produção'), ('reprodução', 'Reprodução'), ('sanidade', 'Sanidade'), ('alimentos', 'Alimentos'), ('administrativo', 'Administrativo'), ('outro', 'Outro')], help_text='Setor de trabalho do funcionário', max_length=100, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='propriedades',
            field=models.ManyToManyField(blank=True, help_text='Propriedades a que o funcionário tem acesso', related_name='usuarios_acesso', to='cadastros.propriedade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], default='proprietario', help_text='Define nível de acesso e permissões no sistema', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usuarios_us_email_41a027_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo_usuario'], name='usuarios_us_tipo_us_c19733_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='usuarios_us_is_acti_8a269b_idx'),
        ),
    ]
