# Generated by Django 5.2.8 on 2026-06-14 00:29

import datumagro.apps.usuarios.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_vacina_informacaogenetica_piquete_fichatecnicaanimal_and_more'),
        ('usuarios', '0003_alter_perfilusuario_options_perfilusuario_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=datumagro.apps.usuarios.models._gerar_token, max_length=72, unique=True)),
                ('codigo', models.CharField(default=datumagro.apps.usuarios.models._gerar_codigo, max_length=6, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('tipo_usuario', models.CharField(choices=[('proprietario', 'Proprietário'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(default=datumagro.apps.usuarios.models._expira_em)),
                ('aceito_por', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convite_aceito', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='cadastros.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite de Equipe',
                'verbose_name_plural': 'Convites de Equipe',
                'ordering': ['-criado_em'],
            },
        ),
    ]
