# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relatorio', models.CharField(choices=[('PDF_DESEMPENHO_LOTE', 'PDF - Desempenho de Lote'), ('EXCEL_LISTA_ANIMAIS', 'Excel - Lista de Animais')], max_length=50)),
                ('status', models.CharField(choices=[('GERANDO', 'Gerando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro na Geração')], default='GERANDO', max_length=20)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/%Y/%m/%d/')),
                ('parametros', models.JSONField(blank=True, help_text='Parâmetros usados na geração (ex: ID do Lote)', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='cadastros.cliente')),
            ],
            options={
                'verbose_name': 'Relatório Gerado',
                'verbose_name_plural': 'Histórico de Relatórios',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
