# Generated by Django 5.2.8 on 2026-06-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='tipo_relatorio',
            field=models.CharField(choices=[('PDF_DESEMPENHO_LOTE', 'PDF - Desempenho de Lote'), ('EXCEL_LISTA_ANIMAIS', 'Excel - Lista de Animais'), ('DESEMPENHO', 'Relatório de Desempenho'), ('FINANCEIRO', 'Relatório Financeiro'), ('SANITARIO', 'Relatório Sanitário'), ('REPRODUTIVO', 'Relatório Reprodutivo'), ('PRODUCAO', 'Relatório de Produção')], max_length=50),
        ),
    ]
