# Generated by Django 5.2.8 on 2026-08-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_slug', models.SlugField(help_text='Identificador da tela. Ex: mapa, pesagem, sanitario, financeiro')),
                ('titulo', models.CharField(max_length=150)),
                ('especie', models.CharField(choices=[('GLOBAL', 'Todas as Atividades'), ('BOVINOS_CORTE', 'Bovinos de Corte'), ('BOVINOS_LEITE', 'Bovinos de Leite'), ('SUINOS', 'Suinocultura'), ('EQUINOS', 'Equinocultura'), ('OVINOS_CAPRINOS', 'Ovinos e Caprinos'), ('TERRA', 'Apenas Terra / Agricultura')], default='GLOBAL', max_length=20)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('como_usar_passo_a_passo', models.TextField()),
                ('dicas_agronomicas_zootecnicas', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guia de Módulo',
                'verbose_name_plural': 'Guias de Módulos',
                'ordering': ['modulo_slug', 'ordem'],
                'unique_together': {('modulo_slug', 'especie')},
            },
        ),
    ]
