# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_integracao', models.CharField(choices=[('RFID_PESAGEM', 'RFID + Pesagem em Balança'), ('RFID_MANEJO', 'RFID em Tronco de Manejo'), ('CAMERA_PESAGEM', 'Câmera de Pesagem (Futuro)')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dados_recebidos', models.JSONField(help_text='O JSON bruto recebido do hardware.')),
                ('status', models.CharField(choices=[('PROCESSADO', 'Processado com Sucesso'), ('ERRO', 'Erro no Processamento'), ('PENDENTE', 'Pendente de Processamento')], default='PENDENTE', max_length=20)),
                ('mensagem_retorno', models.TextField(blank=True, help_text='Mensagem de sucesso ou erro retornada.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_integracao', to='cadastros.cliente')),
            ],
            options={
                'verbose_name': 'Log de Integração',
                'verbose_name_plural': 'Logs de Integração',
                'ordering': ['-timestamp'],
            },
        ),
    ]
