# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPublicoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='URL única para o perfil do animal.', max_length=255, unique=True)),
                ('is_publico', models.BooleanField(default=False, help_text='Controla se a página pública está ativa.')),
                ('titulo_perfil', models.CharField(blank=True, help_text='Ex: Conheça o Lote Premium da Fazenda Modelo', max_length=255)),
                ('historia_destacada', models.TextField(blank=True, help_text='Um texto para o consumidor sobre a origem e qualidade do animal.')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_publico', to='cadastros.animal')),
            ],
            options={
                'verbose_name': 'Perfil Público do Animal',
                'verbose_name_plural': 'Perfis Públicos dos Animais',
            },
        ),
    ]
