# Generated by Django 5.2.6 on 2025-10-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('SANITARIO', 'Alerta Sanitário (Ex: Vacina Atrasada)'), ('REPRODUTIVO', 'Alerta Reprodutivo (Ex: Sugestão de Cobertura)'), ('DESEMPENHO', 'Alerta de Desempenho (Ex: Baixo GMD)'), ('MANEJO', 'Recomendação de Manejo (Ex: Troca de Piquete)'), ('GENETICO', 'Recomendação Genética (Ex: Sugestão de Acasalamento)')], max_length=20)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VISUALIZADO', 'Visualizado'), ('RESOLVIDO', 'Resolvido')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cadastros.animal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cadastros.cliente')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas da IA',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
